name: iOS Release Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'lib/**', 'ios/**', 'pubspec.*', '.github/workflows/ios-build.yml' ]

jobs:
  build-ios:
    runs-on: macos-14
    env:
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Fail fast if any required secret is missing or empty
      - name: Verify required secrets
        run: |
          for var in APPLE_TEAM_ID APPLE_CERTIFICATE_P12 APPLE_CERT_PASSWORD \
              APPLE_PROVISIONING_PROFILE ASC_API_KEY_P8 ASC_KEY_ID ASC_ISSUER_ID; do
            if [ -z "${!var}" ]; then
              echo "::error::${var} is not set or empty"
              exit 1
            fi
          done
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_CERTIFICATE_P12: ${{ secrets.APPLE_CERTIFICATE_P12 }}
          APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
          APPLE_PROVISIONING_PROFILE: ${{ secrets.APPLE_PROVISIONING_PROFILE }}
          ASC_API_KEY_P8: ${{ secrets.ASC_API_KEY_P8 }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Flutter dependencies
        run: flutter pub get

      # Clean any cached iOS build data that might have old bundle ID
      - name: Clean iOS build cache
        run: |
          rm -rf ios/build
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Generated.xcconfig
          flutter clean
          flutter pub get
          flutter build ios --release --no-codesign

      # Extra clean for CocoaPods and Xcode Derived Data
      - name: Clean CocoaPods and Xcode Derived Data
        run: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          pod cache clean --all
          pod install
          cd ..
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      # Import signing certificate & provisioning profile (requires secrets)
      - name: Import code signing certs & profiles
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_P12 }}
          p12-password: ${{ secrets.APPLE_CERT_PASSWORD }}

      # Install provisioning profile
      - name: Install provisioning profile
        env:
          PROVISION_PROFILE: ${{ secrets.APPLE_PROVISIONING_PROFILE }}
        run: |
          # ---- DEBUG: Check secret content ----
          echo "PROVISION_PROFILE length: ${#PROVISION_PROFILE}"
          echo "First 50 chars: ${PROVISION_PROFILE:0:50}"
          if [ ${#PROVISION_PROFILE} -eq 0 ]; then
            echo "::error::APPLE_PROVISIONING_PROFILE secret is completely empty!"
            exit 1
          fi
          
          # ---- ACTUAL WORK ----
          PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          # Ensure the Provisioning Profiles directory exists
          mkdir -p "$PROFILE_DIR"
          echo "$PROVISION_PROFILE" | base64 --decode > "$PROFILE_DIR/profile.mobileprovision"
          # ---- DEBUG: verify decode ----
          PROFILE_PATH="$PROFILE_DIR/profile.mobileprovision"
          BYTES=$(stat -f%z "$PROFILE_PATH")
          echo "Decoded provisioning profile size: ${BYTES} bytes"
          if [ "$BYTES" -eq 0 ]; then
            echo "::error::Decoded provisioning profile is empty – check APPLE_PROVISIONING_PROFILE secret" && exit 1
          fi
          echo "Top of decoded profile plist (should start with <?xml ... >):"
          security cms -D -i "$PROFILE_PATH" | head -n 10
          
          # ---- Extract UUID for xcodebuild ----
          echo "DEBUG: About to extract UUID from same file..."
          echo "DEBUG: File still exists: $(ls -la "$PROFILE_PATH")"
          echo "DEBUG: Testing security cms again..."
          security cms -D -i "$PROFILE_PATH" | head -n 3
          echo "DEBUG: Now extracting UUID..."
          # Decode to temp file since PlistBuddy needs a file path, not stdin
          TEMP_PLIST="/tmp/profile.plist"
          security cms -D -i "$PROFILE_PATH" > "$TEMP_PLIST"
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c "Print:UUID" "$TEMP_PLIST")
          echo "PROFILE_UUID=$PROFILE_UUID" >> $GITHUB_ENV
          echo "Profile UUID: $PROFILE_UUID"

      # Write App Store Connect key (still needed later for fastlane deliver)
      - name: Write ASC API key to disk
        env:
          ASC_API_KEY_P8: ${{ secrets.ASC_API_KEY_P8 }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        run: |
          KEY_PATH="$RUNNER_TEMP/asc_key.p8"
          echo "$ASC_API_KEY_P8" > "$KEY_PATH"
          echo "ASC_KEY_PATH=$KEY_PATH" >> $GITHUB_ENV
          echo "ASC_KEY_ID=$ASC_KEY_ID" >> $GITHUB_ENV
          echo "ASC_ISSUER_ID=$ASC_ISSUER_ID" >> $GITHUB_ENV

      # Build and export IPA via xcodebuild
      - name: Archive with xcodebuild (automatic signing)
        run: |
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/Runner.xcarchive \
            -allowProvisioningUpdates \
            -authenticationKeyPath $ASC_KEY_PATH \
            -authenticationKeyID $ASC_KEY_ID \
            -authenticationKeyIssuerID $ASC_ISSUER_ID \
            DEVELOPMENT_TEAM=$APPLE_TEAM_ID \
            CODE_SIGN_STYLE=Automatic \
            clean archive

      - name: Create ExportOptions.plist for manual signing
        run: |
          cat > ios/ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>$APPLE_TEAM_ID</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>signingCertificate</key>
            <string>Apple Distribution</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>ai.strawberry.japchae</key>
              <string>$PROFILE_UUID</string>
            </dict>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
            <key>destination</key>
            <string>export</string>
          </dict>
          </plist>
          EOF

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/export

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: japchae-ios-ipa
          path: build/export/*.ipa

      # ---- Fastlane: upload to TestFlight ----
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install fastlane
        run: gem install fastlane -N

      - name: Upload to TestFlight via fastlane
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_API_KEY_P8: ${{ secrets.ASC_API_KEY_P8 }}
        run: |
          cd ios && fastlane ios upload_testflight 